version: "3.9"
services:
  kibana:
    image: kibana:latest
    container_name: kibana
    volumes:
      - klibana-data:/usr/share/kibana/data
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=https://ELASTICSEARCH
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 1G
    restart: unless-stopped
volumes:
  klibana-data:
