version: "3.9"

services:
  mariadb:
    image: bitnami/mariadb:latest
    restart: on-failure
    entrypoint :  
      - /bin/sh
      - cat /install-plugins.txt
    env_file:
      - ./stack.env
    volumes:
      - mariadb-pvs:/bitnami/mariadb
      - ./install-plugins.sh:/install-plugins.txt

  # wordpress:
  #   depends_on:
  #     - mariadb
  #   image: bitnami/wordpress-nginx:6
  #   restart: always
  #   ports:
  #     - "18443:8443"
  #   env_file:
  #     - ./stack.env
  #   volumes:
  #     - ./install-plugins.sh:/post-init.d/install-plugins.sh
  #     - ./install-plugins.sh:/docker-entrypoint-init.d/install-plugins.sh
volumes:
  mariadb-pvs:
