version: "3.9"

services:
  mariadb:
    image: nginx:latest
    restart: always
    env_file:
      - stack.env
    volumes:
      - mariadb-pvs:/bitnami/mariadb

  wordpress:
    depends_on:
      - mariadb
    image: nginx:latest
    restart: always
    ports:
      - "18443:8443"
    volumes:
      - ./install-plugins.sh:/post-init.d/install-plugins.sh
      - ./install-plugins.sh:/docker-entrypoint-init.d/install-plugins.sh
volumes:
  mariadb-pvs:
