version: '3'
services:
  influxdb:
    restart: always 
    image: nginx
    ports:
      - "8086:80"
    networks:
      - trailpulse-network
  grafana:
    image: nginx
    networks:
      - trailpulse-network
  
  mongodb:
    restart: always 
    image: nginx:latest
    ports:
      - "27017:80"
    networks:
      - trailpulse-network

networks:
  trailpulse-network:
