name: "Cluster Deploy"
on:
  workflow_dispatch:
    inputs:
      CLUSTER_NAME:
        description: 'Enter a Name for Cluster:'
        type: string
        required: true
      Dataaacenter:
        description: 'DataCenter to deploy the cluster in:'
        type: string
        required: true
      Num of Control Plane Nodes:
        description: "Control plane nodes needed:"
        required: false
        type: string
env:
  SECRET1: ${{ secrets.SECRET1 }}
  VAR1: ${{ vars.VAR1 }}
  CLUSTER_NAME: ${{ inputs.CLUSTER_NAME }}
jobs:
  test:
    runs-on: sdulam
    steps:
      - name: "First Step"
        run: |
          pwd
          env
          echo "Secret: "$SECRET1
          echo "Var: "$VAR1
          echo "ClusterName: ${{ inputs.CLUSTER_NAME }}"
          
